//
// Created by LABCFD on 7/11/2024.
//

#ifndef MODELAGEM_MEMBRANAS_FIBRACILINDRICA_H
#define MODELAGEM_MEMBRANAS_FIBRACILINDRICA_H


class FibraCilindrica {

};


#endif //MODELAGEM_MEMBRANAS_FIBRACILINDRICA_H
