//
// Created by LABCFD on 7/12/2024.
//

#ifndef MODELAGEM_MEMBRANAS_DISTRIBUICAOBASE_H
#define MODELAGEM_MEMBRANAS_DISTRIBUICAOBASE_H


class DistribuicaoBase {

};


#endif //MODELAGEM_MEMBRANAS_DISTRIBUICAOBASE_H
